---
# Jupyterlab
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jupyterlab
spec:
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
      - name: jupyterlab-container
        image: gitlab-registry.nautilus.optiputer.net/oliverevans96/jupyterlab-ipp/jlab
        env:
        - name: SCRATCH
          value: "/scratch"
        volumeMounts:
        - name: scratch-vol
          mountPath: /scratch
        - name: jupyter-config-vol
          mountPath: /home/jovyan/.jupyter
        - name: ipython-config-vol
          mountPath: /home/jovyan/.ipython
      volumes:
      - name: scratch-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/scratch"
      - name: jupyter-config-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/config/jupyter"
      - name: ipython-config-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/config/ipython"

---
# Expose JupyterLab
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-jupyterlab
  labels:
    app: jupyterlab
spec:
  selector:
    app: jupyterlab
  ports:
  - port: 80
    targetPort: 8888

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-jupyterlab
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: oliver-jlab-ipp.nautilus.optiputer.net
    http:
      paths:
      - backend:
          serviceName: traefik-jupyterlab
          servicePort: 80

---
# IPyParallel Cluster
---
# IPController Service
kind: Service
apiVersion: v1
metadata:
  name: ipcontroller-service
spec:
  selector:
    app: ipcontroller
  ports:
  - name: registration
    protocol: TCP
    port: 47137
    targetPort: 47137
  - name: client-control
    protocol: TCP
    port: 58083
    targetPort: 58083
  - name: client-mux
    protocol: TCP
    port: 51855
    targetPort: 51855
  - name: client-task
    protocol: TCP
    port: 44815
    targetPort: 44815
  - name: client-iopub
    protocol: TCP
    port: 43985
    targetPort: 43985
  - name: client-notification
    protocol: TCP
    port: 33805
    targetPort: 33805
  - name: engine-control
    protocol: TCP
    port: 55613
    targetPort: 55613
  - name: engine-mux
    protocol: TCP
    port: 43201
    targetPort: 43201
  - name: engine-hb_ping
    protocol: TCP
    port: 59543
    targetPort: 59543
  - name: engine-hb_pong
    protocol: TCP
    port: 33721
    targetPort: 33721
  - name: engine-task
    protocol: TCP
    port: 46615
    targetPort: 46615
  - name: engine-iopub
    protocol: TCP
    port: 42121
    targetPort: 42121

---
# IPController
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ipcontroller
spec:
  template:
    metadata:
      labels:
        app: ipcontroller
    spec:
      containers:
      - name: ipcontroller-container
        image: gitlab-registry.nautilus.optiputer.net/oliverevans96/jupyterlab-ipp/ipp
        command: ["ipcontroller"]
        args: ["--reuse"]
        env:
        - name: SCRATCH
          value: "/scratch"
        volumeMounts:
        - name: scratch-vol
          mountPath: /scratch
        - name: ipython-config-vol
          mountPath: /root/.ipython
      volumes:
      - name: scratch-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/scratch"
      - name: ipython-config-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/config/ipython"

---
# IPEngine
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ipengine
spec:
  template:
    metadata:
      labels:
        app: ipengine
    spec:
      containers:
      - name: ipengine-container
        image: gitlab-registry.nautilus.optiputer.net/oliverevans96/jupyterlab-ipp/ipp
        command: ["ipengine"]
        env:
        - name: SCRATCH
          value: "/scratch"
        volumeMounts:
        - name: scratch-vol
          mountPath: /scratch
        - name: ipython-config-vol
          mountPath: /root/.ipython
      volumes:
      - name: scratch-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/scratch"
      - name: ipython-config-vol
        nfs:
          server: 10.244.25.108
          path: "/jlab/config/ipython"
